//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cuahangModel", "FK__chitietdo__madon__1FCDBCEB", "dondathang", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication1.dondathang), "chitietdondathang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication1.chitietdondathang), true)]
[assembly: EdmRelationshipAttribute("cuahangModel", "FK__chitietdonda__id__20C1E124", "sanpham", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication1.sanpham), "chitietdondathang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication1.chitietdondathang), true)]
[assembly: EdmRelationshipAttribute("cuahangModel", "FK__chitietho__mahoa__1BFD2C07", "hoadon", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication1.hoadon), "chitiethoadon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication1.chitiethoadon), true)]
[assembly: EdmRelationshipAttribute("cuahangModel", "FK__chitiethoado__id__1CF15040", "sanpham", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WindowsFormsApplication1.sanpham), "chitiethoadon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WindowsFormsApplication1.chitiethoadon), true)]

#endregion

namespace WindowsFormsApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cuahangEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cuahangEntities object using the connection string found in the 'cuahangEntities' section of the application configuration file.
        /// </summary>
        public cuahangEntities() : base("name=cuahangEntities", "cuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cuahangEntities object.
        /// </summary>
        public cuahangEntities(string connectionString) : base(connectionString, "cuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cuahangEntities object.
        /// </summary>
        public cuahangEntities(EntityConnection connection) : base(connection, "cuahangEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<chitietdondathang> chitietdondathangs
        {
            get
            {
                if ((_chitietdondathangs == null))
                {
                    _chitietdondathangs = base.CreateObjectSet<chitietdondathang>("chitietdondathangs");
                }
                return _chitietdondathangs;
            }
        }
        private ObjectSet<chitietdondathang> _chitietdondathangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<chitiethoadon> chitiethoadons
        {
            get
            {
                if ((_chitiethoadons == null))
                {
                    _chitiethoadons = base.CreateObjectSet<chitiethoadon>("chitiethoadons");
                }
                return _chitiethoadons;
            }
        }
        private ObjectSet<chitiethoadon> _chitiethoadons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dondathang> dondathangs
        {
            get
            {
                if ((_dondathangs == null))
                {
                    _dondathangs = base.CreateObjectSet<dondathang>("dondathangs");
                }
                return _dondathangs;
            }
        }
        private ObjectSet<dondathang> _dondathangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hoadon> hoadons
        {
            get
            {
                if ((_hoadons == null))
                {
                    _hoadons = base.CreateObjectSet<hoadon>("hoadons");
                }
                return _hoadons;
            }
        }
        private ObjectSet<hoadon> _hoadons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sanpham> sanphams
        {
            get
            {
                if ((_sanphams == null))
                {
                    _sanphams = base.CreateObjectSet<sanpham>("sanphams");
                }
                return _sanphams;
            }
        }
        private ObjectSet<sanpham> _sanphams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the chitietdondathangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTochitietdondathangs(chitietdondathang chitietdondathang)
        {
            base.AddObject("chitietdondathangs", chitietdondathang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the chitiethoadons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTochitiethoadons(chitiethoadon chitiethoadon)
        {
            base.AddObject("chitiethoadons", chitiethoadon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dondathangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodondathangs(dondathang dondathang)
        {
            base.AddObject("dondathangs", dondathang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hoadons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohoadons(hoadon hoadon)
        {
            base.AddObject("hoadons", hoadon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sanphams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosanphams(sanpham sanpham)
        {
            base.AddObject("sanphams", sanpham);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cuahangModel", Name="chitietdondathang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class chitietdondathang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new chitietdondathang object.
        /// </summary>
        /// <param name="stt">Initial value of the stt property.</param>
        /// <param name="madondathang">Initial value of the madondathang property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static chitietdondathang Createchitietdondathang(global::System.Int32 stt, global::System.Int32 madondathang, global::System.Int32 id)
        {
            chitietdondathang chitietdondathang = new chitietdondathang();
            chitietdondathang.stt = stt;
            chitietdondathang.madondathang = madondathang;
            chitietdondathang.id = id;
            return chitietdondathang;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stt
        {
            get
            {
                return _stt;
            }
            set
            {
                if (_stt != value)
                {
                    OnsttChanging(value);
                    ReportPropertyChanging("stt");
                    _stt = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stt");
                    OnsttChanged();
                }
            }
        }
        private global::System.Int32 _stt;
        partial void OnsttChanging(global::System.Int32 value);
        partial void OnsttChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 madondathang
        {
            get
            {
                return _madondathang;
            }
            set
            {
                if (_madondathang != value)
                {
                    OnmadondathangChanging(value);
                    ReportPropertyChanging("madondathang");
                    _madondathang = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("madondathang");
                    OnmadondathangChanged();
                }
            }
        }
        private global::System.Int32 _madondathang;
        partial void OnmadondathangChanging(global::System.Int32 value);
        partial void OnmadondathangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> soluongdat
        {
            get
            {
                return _soluongdat;
            }
            set
            {
                OnsoluongdatChanging(value);
                ReportPropertyChanging("soluongdat");
                _soluongdat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("soluongdat");
                OnsoluongdatChanged();
            }
        }
        private Nullable<global::System.Int32> _soluongdat;
        partial void OnsoluongdatChanging(Nullable<global::System.Int32> value);
        partial void OnsoluongdatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> soluongnhan
        {
            get
            {
                return _soluongnhan;
            }
            set
            {
                OnsoluongnhanChanging(value);
                ReportPropertyChanging("soluongnhan");
                _soluongnhan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("soluongnhan");
                OnsoluongnhanChanged();
            }
        }
        private Nullable<global::System.Int32> _soluongnhan;
        partial void OnsoluongnhanChanging(Nullable<global::System.Int32> value);
        partial void OnsoluongnhanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> gianhap
        {
            get
            {
                return _gianhap;
            }
            set
            {
                OngianhapChanging(value);
                ReportPropertyChanging("gianhap");
                _gianhap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gianhap");
                OngianhapChanged();
            }
        }
        private Nullable<global::System.Decimal> _gianhap;
        partial void OngianhapChanging(Nullable<global::System.Decimal> value);
        partial void OngianhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trangthai
        {
            get
            {
                return _trangthai;
            }
            set
            {
                OntrangthaiChanging(value);
                ReportPropertyChanging("trangthai");
                _trangthai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trangthai");
                OntrangthaiChanged();
            }
        }
        private global::System.String _trangthai;
        partial void OntrangthaiChanging(global::System.String value);
        partial void OntrangthaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lido
        {
            get
            {
                return _lido;
            }
            set
            {
                OnlidoChanging(value);
                ReportPropertyChanging("lido");
                _lido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lido");
                OnlidoChanged();
            }
        }
        private global::System.String _lido;
        partial void OnlidoChanging(global::System.String value);
        partial void OnlidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tinhtrang
        {
            get
            {
                return _tinhtrang;
            }
            set
            {
                OntinhtrangChanging(value);
                ReportPropertyChanging("tinhtrang");
                _tinhtrang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tinhtrang");
                OntinhtrangChanged();
            }
        }
        private global::System.String _tinhtrang;
        partial void OntinhtrangChanging(global::System.String value);
        partial void OntinhtrangChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietdo__madon__1FCDBCEB", "dondathang")]
        public dondathang dondathang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "dondathang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "dondathang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dondathang> dondathangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "dondathang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "dondathang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietdonda__id__20C1E124", "sanpham")]
        public sanpham sanpham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitietdonda__id__20C1E124", "sanpham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitietdonda__id__20C1E124", "sanpham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sanpham> sanphamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitietdonda__id__20C1E124", "sanpham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sanpham>("cuahangModel.FK__chitietdonda__id__20C1E124", "sanpham", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cuahangModel", Name="chitiethoadon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class chitiethoadon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new chitiethoadon object.
        /// </summary>
        /// <param name="stt">Initial value of the stt property.</param>
        /// <param name="mahoadon">Initial value of the mahoadon property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static chitiethoadon Createchitiethoadon(global::System.Int32 stt, global::System.Int32 mahoadon, global::System.Int32 id)
        {
            chitiethoadon chitiethoadon = new chitiethoadon();
            chitiethoadon.stt = stt;
            chitiethoadon.mahoadon = mahoadon;
            chitiethoadon.id = id;
            return chitiethoadon;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stt
        {
            get
            {
                return _stt;
            }
            set
            {
                if (_stt != value)
                {
                    OnsttChanging(value);
                    ReportPropertyChanging("stt");
                    _stt = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stt");
                    OnsttChanged();
                }
            }
        }
        private global::System.Int32 _stt;
        partial void OnsttChanging(global::System.Int32 value);
        partial void OnsttChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mahoadon
        {
            get
            {
                return _mahoadon;
            }
            set
            {
                if (_mahoadon != value)
                {
                    OnmahoadonChanging(value);
                    ReportPropertyChanging("mahoadon");
                    _mahoadon = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mahoadon");
                    OnmahoadonChanged();
                }
            }
        }
        private global::System.Int32 _mahoadon;
        partial void OnmahoadonChanging(global::System.Int32 value);
        partial void OnmahoadonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> giaban
        {
            get
            {
                return _giaban;
            }
            set
            {
                OngiabanChanging(value);
                ReportPropertyChanging("giaban");
                _giaban = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("giaban");
                OngiabanChanged();
            }
        }
        private Nullable<global::System.Decimal> _giaban;
        partial void OngiabanChanging(Nullable<global::System.Decimal> value);
        partial void OngiabanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> soluongmua
        {
            get
            {
                return _soluongmua;
            }
            set
            {
                OnsoluongmuaChanging(value);
                ReportPropertyChanging("soluongmua");
                _soluongmua = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("soluongmua");
                OnsoluongmuaChanged();
            }
        }
        private Nullable<global::System.Int32> _soluongmua;
        partial void OnsoluongmuaChanging(Nullable<global::System.Int32> value);
        partial void OnsoluongmuaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietho__mahoa__1BFD2C07", "hoadon")]
        public hoadon hoadon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<hoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "hoadon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<hoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "hoadon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<hoadon> hoadonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<hoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "hoadon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<hoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "hoadon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitiethoado__id__1CF15040", "sanpham")]
        public sanpham sanpham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitiethoado__id__1CF15040", "sanpham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitiethoado__id__1CF15040", "sanpham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sanpham> sanphamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sanpham>("cuahangModel.FK__chitiethoado__id__1CF15040", "sanpham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sanpham>("cuahangModel.FK__chitiethoado__id__1CF15040", "sanpham", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cuahangModel", Name="dondathang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dondathang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dondathang object.
        /// </summary>
        /// <param name="madondathang">Initial value of the madondathang property.</param>
        public static dondathang Createdondathang(global::System.Int32 madondathang)
        {
            dondathang dondathang = new dondathang();
            dondathang.madondathang = madondathang;
            return dondathang;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 madondathang
        {
            get
            {
                return _madondathang;
            }
            set
            {
                if (_madondathang != value)
                {
                    OnmadondathangChanging(value);
                    ReportPropertyChanging("madondathang");
                    _madondathang = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("madondathang");
                    OnmadondathangChanged();
                }
            }
        }
        private global::System.Int32 _madondathang;
        partial void OnmadondathangChanging(global::System.Int32 value);
        partial void OnmadondathangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngaydathang
        {
            get
            {
                return _ngaydathang;
            }
            set
            {
                OnngaydathangChanging(value);
                ReportPropertyChanging("ngaydathang");
                _ngaydathang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngaydathang");
                OnngaydathangChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngaydathang;
        partial void OnngaydathangChanging(Nullable<global::System.DateTime> value);
        partial void OnngaydathangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nhacungcap
        {
            get
            {
                return _nhacungcap;
            }
            set
            {
                OnnhacungcapChanging(value);
                ReportPropertyChanging("nhacungcap");
                _nhacungcap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nhacungcap");
                OnnhacungcapChanged();
            }
        }
        private global::System.String _nhacungcap;
        partial void OnnhacungcapChanging(global::System.String value);
        partial void OnnhacungcapChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietdo__madon__1FCDBCEB", "chitietdondathang")]
        public EntityCollection<chitietdondathang> chitietdondathangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<chitietdondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "chitietdondathang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<chitietdondathang>("cuahangModel.FK__chitietdo__madon__1FCDBCEB", "chitietdondathang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cuahangModel", Name="hoadon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hoadon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hoadon object.
        /// </summary>
        /// <param name="mahoadon">Initial value of the mahoadon property.</param>
        public static hoadon Createhoadon(global::System.Int32 mahoadon)
        {
            hoadon hoadon = new hoadon();
            hoadon.mahoadon = mahoadon;
            return hoadon;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mahoadon
        {
            get
            {
                return _mahoadon;
            }
            set
            {
                if (_mahoadon != value)
                {
                    OnmahoadonChanging(value);
                    ReportPropertyChanging("mahoadon");
                    _mahoadon = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mahoadon");
                    OnmahoadonChanged();
                }
            }
        }
        private global::System.Int32 _mahoadon;
        partial void OnmahoadonChanging(global::System.Int32 value);
        partial void OnmahoadonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngayban
        {
            get
            {
                return _ngayban;
            }
            set
            {
                OnngaybanChanging(value);
                ReportPropertyChanging("ngayban");
                _ngayban = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngayban");
                OnngaybanChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngayban;
        partial void OnngaybanChanging(Nullable<global::System.DateTime> value);
        partial void OnngaybanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> tienkhachdua
        {
            get
            {
                return _tienkhachdua;
            }
            set
            {
                OntienkhachduaChanging(value);
                ReportPropertyChanging("tienkhachdua");
                _tienkhachdua = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tienkhachdua");
                OntienkhachduaChanged();
            }
        }
        private Nullable<global::System.Decimal> _tienkhachdua;
        partial void OntienkhachduaChanging(Nullable<global::System.Decimal> value);
        partial void OntienkhachduaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietho__mahoa__1BFD2C07", "chitiethoadon")]
        public EntityCollection<chitiethoadon> chitiethoadons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<chitiethoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "chitiethoadon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<chitiethoadon>("cuahangModel.FK__chitietho__mahoa__1BFD2C07", "chitiethoadon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cuahangModel", Name="sanpham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sanpham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sanpham object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="masp">Initial value of the masp property.</param>
        /// <param name="tensp">Initial value of the tensp property.</param>
        public static sanpham Createsanpham(global::System.Int32 id, global::System.String masp, global::System.String tensp)
        {
            sanpham sanpham = new sanpham();
            sanpham.id = id;
            sanpham.masp = masp;
            sanpham.tensp = tensp;
            return sanpham;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String masp
        {
            get
            {
                return _masp;
            }
            set
            {
                OnmaspChanging(value);
                ReportPropertyChanging("masp");
                _masp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("masp");
                OnmaspChanged();
            }
        }
        private global::System.String _masp;
        partial void OnmaspChanging(global::System.String value);
        partial void OnmaspChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tensp
        {
            get
            {
                return _tensp;
            }
            set
            {
                OntenspChanging(value);
                ReportPropertyChanging("tensp");
                _tensp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tensp");
                OntenspChanged();
            }
        }
        private global::System.String _tensp;
        partial void OntenspChanging(global::System.String value);
        partial void OntenspChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.String _size;
        partial void OnsizeChanging(global::System.String value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hang
        {
            get
            {
                return _hang;
            }
            set
            {
                OnhangChanging(value);
                ReportPropertyChanging("hang");
                _hang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hang");
                OnhangChanged();
            }
        }
        private global::System.String _hang;
        partial void OnhangChanging(global::System.String value);
        partial void OnhangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> giamgia
        {
            get
            {
                return _giamgia;
            }
            set
            {
                OngiamgiaChanging(value);
                ReportPropertyChanging("giamgia");
                _giamgia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("giamgia");
                OngiamgiaChanged();
            }
        }
        private Nullable<global::System.Double> _giamgia;
        partial void OngiamgiaChanging(Nullable<global::System.Double> value);
        partial void OngiamgiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> soluongtonkho
        {
            get
            {
                return _soluongtonkho;
            }
            set
            {
                OnsoluongtonkhoChanging(value);
                ReportPropertyChanging("soluongtonkho");
                _soluongtonkho = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("soluongtonkho");
                OnsoluongtonkhoChanged();
            }
        }
        private Nullable<global::System.Int32> _soluongtonkho;
        partial void OnsoluongtonkhoChanging(Nullable<global::System.Int32> value);
        partial void OnsoluongtonkhoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> giaban
        {
            get
            {
                return _giaban;
            }
            set
            {
                OngiabanChanging(value);
                ReportPropertyChanging("giaban");
                _giaban = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("giaban");
                OngiabanChanged();
            }
        }
        private Nullable<global::System.Decimal> _giaban;
        partial void OngiabanChanging(Nullable<global::System.Decimal> value);
        partial void OngiabanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngaynhap
        {
            get
            {
                return _ngaynhap;
            }
            set
            {
                OnngaynhapChanging(value);
                ReportPropertyChanging("ngaynhap");
                _ngaynhap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngaynhap");
                OnngaynhapChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngaynhap;
        partial void OnngaynhapChanging(Nullable<global::System.DateTime> value);
        partial void OnngaynhapChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitietdonda__id__20C1E124", "chitietdondathang")]
        public EntityCollection<chitietdondathang> chitietdondathangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<chitietdondathang>("cuahangModel.FK__chitietdonda__id__20C1E124", "chitietdondathang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<chitietdondathang>("cuahangModel.FK__chitietdonda__id__20C1E124", "chitietdondathang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cuahangModel", "FK__chitiethoado__id__1CF15040", "chitiethoadon")]
        public EntityCollection<chitiethoadon> chitiethoadons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<chitiethoadon>("cuahangModel.FK__chitiethoado__id__1CF15040", "chitiethoadon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<chitiethoadon>("cuahangModel.FK__chitiethoado__id__1CF15040", "chitiethoadon", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
